from dataclasses import dataclass, field
from typing import List, Dict


@dataclass
class Candidate:
    """
    Structured candidate profile received from Module 2.
    """

    candidate_id: str

    skills: List[str] = field(default_factory=list)

    experience_years: float = 0.0

    projects: List[str] = field(default_factory=list)

    education: List[str] = field(default_factory=list)

    certifications: List[str] = field(default_factory=list)

    behavioral_signals: Dict[str, float] = field(default_factory=dict)

    career_history: List[Dict] = field(default_factory=list)


@dataclass
class JobRequirements:
    """
    Structured job requirements received from Module 1.
    """

    mandatory_skills: List[str] = field(default_factory=list)

    preferred_skills: List[str] = field(default_factory=list)

    positive_signals: List[str] = field(default_factory=list)

    negative_signals: List[str] = field(default_factory=list)

    weights: Dict[str, float] = field(default_factory=dict)


@dataclass
class CandidateScore:
    """
    Final ranking result generated by Module 3.
    """

    candidate_id: str

    technical_score: float = 0.0

    experience_score: float = 0.0

    project_score: float = 0.0

    behavioral_score: float = 0.0

    education_score: float = 0.0

    culture_score: float = 0.0

    final_score: float = 0.0

    strengths: List[str] = field(default_factory=list)

    weaknesses: List[str] = field(default_factory=list)